#!/usr/bin/env python3
"""Register our trainers with an installed nnunetv2 package.

nnU-Net resolves ``-tr ClassName`` by scanning
``nnunetv2/training/nnUNetTrainer/`` for a class of that name. Our trainers live
in this repository under ``src/vesuvius_surface/training/trainers/``, so this
script drops a small shim module into the installed package that re-exports them.

Idempotent — re-running updates the shim without touching anything else.
Does **not** modify any other nnU-Net file.

    export PYTHONPATH=/path/to/vesuvius-surface/src:$PYTHONPATH
    python scripts/register_nnunet_trainers.py
    python scripts/register_nnunet_trainers.py --check
"""

from __future__ import annotations

import argparse
import importlib
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

SHIM_NAME = "vesuvius_surface_trainers.py"

TRAINER_NAMES = (
    "nnUNetTrainerSkeletonRecall",
    "nnUNetTrainerSkeletonRecall_w05",
    "nnUNetTrainerSkeletonRecall_w2",
    "nnUNetTrainerSkeletonRecall_w4",
    "nnUNetTrainerSkeletonRecall_notube",
    "nnUNetTrainerSkeletonRecall_100epochs",
    "nnUNetTrainerSkeletonRecall_20epochs",
    "nnUNetTrainerSkeletonRecall_700epochs",
    "nnUNetTrainerAffinity",
    "nnUNetTrainerAffinity_w01",
    "nnUNetTrainerAffinity_w05",
    "nnUNetTrainerAffinity_w2",
    "nnUNetTrainerAffinity_shortrange",
    "nnUNetTrainerAffinity_allpairs",
    "nnUNetTrainerAffinity_100epochs",
    "nnUNetTrainerAffinity_700epochs",
    "nnUNetTrainerSkeletonRecallAffinity",
    "nnUNetTrainerSkeletonRecallAffinity_1epoch",
    "nnUNetTrainerSkeletonRecallCascadeLastLayers_10epochs",
    "nnUNetTrainerSkeletonRecallCascadeLastLayers_1epoch",
    "nnUNetTrainerSeeded",
    "nnUNetTrainerSeeded_100epochs",
    "nnUNetTrainerSeeded_ClDice_ScheduleFree",
    "nnUNetTrainerSeeded_ClDice_ScheduleFree_350epochs",
    "STUNetTrainer",
    "STUNetTrainer_small",
    "STUNetTrainer_small_ft",
    "STUNetTrainer_base",
    "STUNetTrainer_base_ft",
    "STUNetTrainer_base_ft_30epochs",
    "STUNetTrainer_large",
    "STUNetTrainer_large_ft",
    "STUNetTrainer_huge",
    "STUNetTrainer_huge_ft",
)


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument(
        "--check",
        action="store_true",
        help="Only verify that each trainer is importable; do not write the shim.",
    )
    p.add_argument(
        "--remove",
        action="store_true",
        help="Delete the shim instead of writing it.",
    )
    return p.parse_args()


def find_trainer_dir() -> Path:
    try:
        import nnunetv2
    except ImportError as exc:
        raise SystemExit(
            "nnunetv2 is not importable in this environment.\n"
            "Activate the training env and install nnunetv2, then re-run.\n"
            f"Detail: {exc}"
        ) from exc

    package_root = Path(nnunetv2.__file__).resolve().parent
    trainer_dir = package_root / "training" / "nnUNetTrainer"
    if not trainer_dir.is_dir():
        raise SystemExit(
            f"Expected trainer directory at {trainer_dir}, but it is missing.\n"
            f"Installed nnunetv2 at {package_root}. This layout may have changed."
        )
    return trainer_dir


def shim_contents() -> str:
    # Built line-by-line rather than via a dedented f-string template: TRAINER_NAMES's own
    # multi-line interpolation doesn't share the template's source indentation, which broke
    # textwrap.dedent()'s common-leading-whitespace detection and produced invalid (partially
    # indented) Python -- a real IndentationError hit and fixed here, not a hypothetical.
    lines = [
        '"""Shim: re-export vesuvius-surface trainers into nnU-Net\'s discovery path.',
        "",
        "Generated by scripts/register_nnunet_trainers.py. Do not edit by hand —",
        "re-run the script after pulling. Requires ``src/`` on PYTHONPATH.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from vesuvius_surface.training.trainers import (",
        "    " + ", ".join(TRAINER_NAMES),
        ")",
        "",
        "__all__ = [",
    ]
    lines += [f'    "{n}",' for n in TRAINER_NAMES]
    lines += ["]", ""]
    return "\n".join(lines)


def check_imports() -> int:
    failed = []
    for name in TRAINER_NAMES:
        try:
            module = importlib.import_module("vesuvius_surface.training.trainers")
            getattr(module, name)
            print(f"  OK  {name}")
        except Exception as exc:  # noqa: BLE001 - report each failure
            print(f"FAIL  {name}: {exc}")
            failed.append(name)
    if failed:
        print(f"\n{len(failed)} trainer(s) failed to import.")
        print("Is src/ on PYTHONPATH?  export PYTHONPATH=.../vesuvius-surface/src:$PYTHONPATH")
        return 1
    print(f"\nAll {len(TRAINER_NAMES)} trainers importable.")
    return 0


def main() -> int:
    args = parse_args()

    if args.check:
        print("Checking trainer imports (src/vesuvius_surface/training/trainers)...")
        return check_imports()

    trainer_dir = find_trainer_dir()
    shim_path = trainer_dir / SHIM_NAME

    if args.remove:
        if shim_path.exists():
            shim_path.unlink()
            print(f"Removed {shim_path}")
        else:
            print(f"No shim at {shim_path}")
        return 0

    shim_path.write_text(shim_contents(), encoding="utf-8")
    print(f"Wrote {shim_path}")
    print()
    print("Verify with:")
    print("  export PYTHONPATH=/path/to/vesuvius-surface/src:$PYTHONPATH")
    print("  python scripts/register_nnunet_trainers.py --check")
    print()
    print("Then launch, e.g.:")
    print("  bash scripts/nnunet_train_topology.sh --stage skelrecall")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
